### ISSUE TITLE
TypeError: can only concatenate str (not "bytes") to str

### ISSUE THREAD

**Issue by digizeph** [CAIDA/pywandio#18]
Python3 version issue:
```
mingwei@hammer01:~/Warehouse/caida-git/libbgpstream$ pywandio-cat swift://bgp-hijacks-edges/year=2020/month=04/day=30/hour=00/edges.1588205400.events.gz
Traceback (most recent call last):
  File "/usr/local/bin/pywandio-cat", line 11, in <module>
    load_entry_point('pywandio==0.1', 'console_scripts', 'pywandio-cat')()
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/opener.py", line 147, in read_main
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/opener.py", line 43, in __init__
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/compressed.py", line 126, in __init__
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/compressed.py", line 17, in __init__
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/compressed.py", line 44, in _refill
TypeError: can only concatenate str (not "bytes") to str
```
Older version does not have this issue.

**Comment by digizeph** [comment]
To reproduce:
```
pywandio-cat swift://bgp-hijacks-triplets-weekly/year=2015/month=02/day=27/triplets-weekly.1424995200.gz|head
Traceback (most recent call last):
  File "/usr/local/bin/pywandio-cat", line 11, in <module>
    load_entry_point('pywandio==0.1', 'console_scripts', 'pywandio-cat')()
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/opener.py", line 147, in read_main
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/opener.py", line 43, in __init__
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/compressed.py", line 126, in __init__
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/compressed.py", line 17, in __init__
  File "/usr/local/lib/python3.7/site-packages/pywandio-0.1-py3.7.egg/wandio/compressed.py", line 44, in _refill
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by digizeph** [comment]
Turned out this error is caused by using a wrong version of the pywandio on my Mac. After full uninstall old versions (including the `.egg` files) and reinstall the 0.2 version, it works now.

The lesson is that, for any library that's dependent on pywandio, it needs to require `pywandio>=2.0`
